export const PENGJUAN_STATUS_DATA = [
  {
    id: "1",
    pegawaiId: "peg-001",
    nip: "198901010001",
    nama: "Rasyid",
    statusLama: "Tanpa Keterangan",
    statusBaru: "Dinas Luar",
    dokumen: "surat_tugas.pdf",
    tanggal: "25 Mei 2026 09:15",
    waktu: "09:15",
    statusVerifikasi: "menunggu",
    analisisAI: null,
  },
  {
    id: "2",
    pegawaiId: "peg-002",
    nip: "199205050002",
    nama: "Ahmad Fauzi",
    statusLama: "Tanpa Keterangan",
    statusBaru: "Sakit",
    dokumen: "surat_dokter.pdf",
    tanggal: "25 Mei 2026 08:45",
    waktu: "08:45",
    statusVerifikasi: "menunggu",
    analisisAI: null,
  },
  {
    id: "3",
    pegawaiId: "peg-003",
    nip: "199508120003",
    nama: "Siti Rahma",
    statusLama: "Tanpa Keterangan",
    statusBaru: "Izin",
    dokumen: "surat_izin.pdf",
    tanggal: "25 Mei 2026 07:30",
    waktu: "07:30",
    statusVerifikasi: "disetujui",
    analisisAI: null,
  },
];
